<?php
	define("CONFIG_SITEADDRESS", "http://localhost:81/magnus/");
	define("CONFIG_SITEEMAIL", "contact@magnus.com");
	define("CONFIG_SITENAME", "Magnus");
	define("CONFIG_SITEOWNER", "Magnus Team");
	
	define("CONFIG_PLAYERSTARTLOOKBODY", 0);
	define("CONFIG_PLAYERSTARTLOOKFEET", 0);
	define("CONFIG_PLAYERSTARTLOOKHEAD", 0);
	define("CONFIG_PLAYERSTARTLOOKLEGS", 0);
	define("CONFIG_PLAYERSTARTLOOKTYPECM", 75);
	define("CONFIG_PLAYERSTARTLOOKTYPEFEMALE", 136);
	define("CONFIG_PLAYERSTARTLOOKTYPEGOD", 266);
	define("CONFIG_PLAYERSTARTLOOKTYPEMALE", 128);
	
	define("CONFIG_PLAYERSTARTCAP", 400);
	define("CONFIG_PLAYERSTARTEXP", 0);
	define("CONFIG_PLAYERSTARTHEALTH", 150);
	define("CONFIG_PLAYERSTARTLEVEL", 1);
	define("CONFIG_PLAYERSTARTLOSSEXP", 2);
	define("CONFIG_PLAYERSTARTLOSSITEMS", 2);
	define("CONFIG_PLAYERSTARTLOSSMANA", 2);
	define("CONFIG_PLAYERSTARTLOSSKILLS", 2);
	define("CONFIG_PLAYERSTARTMANA", 0);
	define("CONFIG_PLAYERSTARTMAGICLEVEL", 0);
	define("CONFIG_PLAYERSTARTPOSX", 432);
	define("CONFIG_PLAYERSTARTPOSY", 480);
	define("CONFIG_PLAYERSTARTPOSZ", 7);
	define("CONFIG_PLAYERSTARTSOUL", 100);
	define("CONFIG_PLAYERSTARTTOWNID", 1);
	
	define("CONFIG_PLAYERROOKSTARTCAP", 400);
	define("CONFIG_PLAYERROOKSTARTEXP", 0);
	define("CONFIG_PLAYERROOKSTARTHEALTH", 150);
	define("CONFIG_PLAYERROOKSTARTLEVEL", 1);
	define("CONFIG_PLAYERROOKSTARTLOSSEXP", 2);
	define("CONFIG_PLAYERROOKSTARTLOSSITEMS", 2);
	define("CONFIG_PLAYERROOKSTARTLOSSMANA", 2);
	define("CONFIG_PLAYERROOKSTARTLOSSKILLS", 2);
	define("CONFIG_PLAYERROOKSTARTMANA", 0);
	define("CONFIG_PLAYERROOKSTARTMAGICLEVEL", 0);
	define("CONFIG_PLAYERROOKSTARTPOSX", 432);
	define("CONFIG_PLAYERROOKSTARTPOSY", 480);
	define("CONFIG_PLAYERROOKSTARTPOSZ", 7);
	define("CONFIG_PLAYERROOKSTARTSOUL", 100);
	define("CONFIG_PLAYERROOKSTARTTOWNID", 1);
	
	define("MYSQL_DB", "magnus");
	define("MYSQL_HOST", "localhost");
	define("MYSQL_PASS", "");
	define("MYSQL_USER", "root");
?>