<?php
	define("CONFIG_SITEADDRESS", "http://localhost:81/magnus/");
	define("CONFIG_SITEEMAIL", "contact@magnus.com");
	define("CONFIG_SITENAME", "Magnus");
	define("CONFIG_SITEOWNER", "Magnus Team");
	
	define("CONFIG_CHARACTERSTARTLOOKBODY", 0);
	define("CONFIG_CHARACTERSTARTLOOKFEET", 0);
	define("CONFIG_CHARACTERSTARTLOOKHEAD", 0);
	define("CONFIG_CHARACTERSTARTLOOKLEGS", 0);
	define("CONFIG_CHARACTERSTARTLOOKTYPECM", 75);
	define("CONFIG_CHARACTERSTARTLOOKTYPEFEMALE", 136);
	define("CONFIG_CHARACTERSTARTLOOKTYPEGOD", 266);
	define("CONFIG_CHARACTERSTARTLOOKTYPEMALE", 128);
	
	define("CONFIG_CHARACTERSTARTCAP", 400);
	define("CONFIG_CHARACTERSTARTEXP", 0);
	define("CONFIG_CHARACTERSTARTHEALTH", 150);
	define("CONFIG_CHARACTERSTARTLEVEL", 1);
	define("CONFIG_CHARACTERSTARTLOSSEXP", 2);
	define("CONFIG_CHARACTERSTARTLOSSITEMS", 2);
	define("CONFIG_CHARACTERSTARTLOSSMANA", 2);
	define("CONFIG_CHARACTERSTARTLOSSKILLS", 2);
	define("CONFIG_CHARACTERSTARTMANA", 0);
	define("CONFIG_CHARACTERSTARTMAGICLEVEL", 0);
	define("CONFIG_CHARACTERSTARTPOSX", 432);
	define("CONFIG_CHARACTERSTARTPOSY", 480);
	define("CONFIG_CHARACTERSTARTPOSZ", 7);
	define("CONFIG_CHARACTERSTARTSOUL", 100);
	define("CONFIG_CHARACTERSTARTTOWNID", 1);
	
	define("CONFIG_CHARACTERROOKSTARTCAP", 400);
	define("CONFIG_CHARACTERROOKSTARTEXP", 0);
	define("CONFIG_CHARACTERROOKSTARTHEALTH", 150);
	define("CONFIG_CHARACTERROOKSTARTLEVEL", 1);
	define("CONFIG_CHARACTERROOKSTARTLOSSEXP", 2);
	define("CONFIG_CHARACTERROOKSTARTLOSSITEMS", 2);
	define("CONFIG_CHARACTERROOKSTARTLOSSMANA", 2);
	define("CONFIG_CHARACTERROOKSTARTLOSSKILLS", 2);
	define("CONFIG_CHARACTERROOKSTARTMANA", 0);
	define("CONFIG_CHARACTERROOKSTARTMAGICLEVEL", 0);
	define("CONFIG_CHARACTERROOKSTARTPOSX", 432);
	define("CONFIG_CHARACTERROOKSTARTPOSY", 480);
	define("CONFIG_CHARACTERROOKSTARTPOSZ", 7);
	define("CONFIG_CHARACTERROOKSTARTSOUL", 100);
	define("CONFIG_CHARACTERROOKSTARTTOWNID", 1);
	
	define("MYSQL_DB", "magnus");
	define("MYSQL_HOST", "localhost");
	define("MYSQL_PASS", "");
	define("MYSQL_USER", "root");
	
	define("SMTP_HOST", "smtp.darghos.com");
	define("SMTP_PASS", "***REMOVED***");
	define("SMTP_USER", "auto-responder@darghos.com");
?>